# Generated by Django 5.2.8 on 2025-11-18 16:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('responsavel', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(default=datetime.time(7, 0))),
                ('hora_fim', models.TimeField(default=datetime.time(19, 0))),
                ('duracao_reserva_minutos', models.IntegerField(default=120)),
                ('quantidade_agendamento_por_apartamento', models.IntegerField(default=2)),
                ('tempo_lembrete_entrada_minutos', models.IntegerField(default=5)),
                ('tempo_lembrete_saida_minutos', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('hora_saida', models.TimeField()),
                ('andar', models.IntegerField(choices=[(0, 'Térreo'), (1, '1º Andar')], default=0)),
                ('phone_number', models.CharField(max_length=13)),
                ('lembrete_entrada_enviado', models.BooleanField(default=False)),
                ('lembrete_saida_enviado', models.BooleanField(default=False)),
                ('enviar_lembrete', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apartamento')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['data', 'hora'],
                'constraints': [models.UniqueConstraint(fields=('data', 'hora', 'andar'), name='unique_reserva')],
            },
        ),
    ]
