# Generated by Django 5.2.8 on 2025-11-18 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='hora_fim',
            field=models.TimeField(default=datetime.time(21, 0)),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
