# Generated by Django 5.2.8 on 2025-11-18 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_configuracao_hora_fim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='quantidade_agendamento_por_apartamento',
            field=models.IntegerField(default=2),
        ),
    ]
