# Generated by Django 5.2.8 on 2025-11-18 01:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_configuracao_quantidade_agendamento_por_apartamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='hora_fim',
            field=models.TimeField(default=datetime.time(19, 0)),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
    ]
