# Generated by Django 5.2.8 on 2025-11-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_configuracao_hora_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='hora_saida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
