# Generated by Django 5.2.8 on 2025-11-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reserva_hora_saida'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='lembrete_entrada_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='lembrete_saida_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='phone_number',
            field=models.CharField(default=5584999999999, max_length=13),
            preserve_default=False,
        ),
    ]
