# Generated by Django 5.2.8 on 2025-11-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reserva_lembrete_entrada_enviado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='enviar_lembrete',
            field=models.BooleanField(default=False),
        ),
    ]
